title: "Blog de Cristian Hernández"
description: "Blog para el curso de Ingeniería de Software."
theme: jekyll-theme-minimal
author: "Cristian Hernández"
show_downloads: false
google_analytics: G-E56VY7ZC7Q