title: "Blog de Cristian Hernández"
logo: /assets/img/logo_umg.png
description: "<b>Curso:</b> Ingeniería de Software<br><b>Docente:</b> Ing. Carlos Godínez<br><b>Estudiante:</b> Cristian Alexander Hernández de León<br><b>Carné:</b> 0903-22-19434"
theme: jekyll-theme-minimal
author: "Cristian Hernández"
show_downloads: false
google_analytics: G-E56VY7ZC7Q